### ISSUE TITLE
hiredis not found

### ISSUE THREAD

**Issue by r-barnes** [MemoryMmy/HiVision#10]
It looks like the `hiredis` and some other libraries are required for compilation. Marking them like
```
find_package(hiredis REQUIRED)
```
would probably be good.

It would also be useful if you could provide prerequisite installation instructions (where this is feasible) in the README. For instance, to get `hiredis` on a Debian-Linux one would type:
```
sudo apt install libhiredis-dev
```
A copy-and-paste line which installs appropriate dependencies would be nice.

**Comment by MemoryMmy** [comment]
We have addressed the issue and added a tutorial for installing the software from source code (https://github.com/MemoryMmy/HiVision/blob/master/dep_software/dep_software_install.txt).

**Comment by r-barnes** [comment]
Thanks!
