### ISSUE TITLE
Can you update Boost?

### ISSUE THREAD

**Issue by r-barnes** [MemoryMmy/HiVision#11]
Your recommended version of Boost (1.64) came out in April 2017. My version (1.71) has some API-breaking changes ([e.g. this](https://stackoverflow.com/questions/56225374/alternative-to-missing-method-in-last-version-of-boost-asio-library)).

If a full update isn't possible do to system limitations on your end, I could work with you to develop some preprocessing directives to handle the API differences.

**Comment by MemoryMmy** [comment]
Yes, we have updated HiVision to support Boost (1.71) and (1.72).

**Comment by r-barnes** [comment]
This worked, thanks.
