### ISSUE TITLE
Inconsistent Indentation

### ISSUE THREAD

**Issue by r-barnes** [MemoryMmy/HiVision#13]
The code has inconsistent indentation. [Here](https://github.com/MemoryMmy/HiVision/blob/master/HiVision_code/src/server.cpp#L101-L115) is one example.

Indentation should only be used when it has meaning; this looks random to me.

Running your entire code through [ClangFormat](https://clang.llvm.org/docs/ClangFormat.html) is one way of fixing this and a number of other stylistic problems, such as using tabs instead of spaces, not alphabetizing includes, &c. If you are using [VS Code](https://code.visualstudio.com/) this is easy to do by using the [clang-format plugin](https://marketplace.visualstudio.com/items?itemName=xaver.clang-format).

Reading the [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html) or a number of other style guides will explain the pros and cons of a number of stylistic choices along with providing an authoritative reference source.

If the plugin produces dissatisfactory results, [this page](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) links to a number of style guides that clang-format knows about and can use.

**Comment by MemoryMmy** [comment]
Thanks for your suggestion, we have addressed this issue.
