### ISSUE TITLE
Makefile references user directories

### ISSUE THREAD

**Issue by r-barnes** [MemoryMmy/HiVision#2]
The Makefile references user directories [here](https://github.com/MemoryMmy/HiVision/blob/add6d2bfc8c880bdddae2c747047b4a3694c7060/HiVision_code/Makefile#L1).

I suggest using `CMake` instead of a makefile for greater portability (see [this](https://github.com/jtebert/kilosim/blob/master/CMakeLists.txt) for instance).

**Comment by MemoryMmy** [comment]
Thanks for your suggestion.  I have applied Cmake in Version 0.2.0.

**Comment by r-barnes** [comment]
Thanks!
