### ISSUE TITLE
Main function is too long

### ISSUE THREAD

**Issue by r-barnes** [MemoryMmy/HiVision#3]
Your [main function](https://github.com/MemoryMmy/HiVision/blob/add6d2bfc8c880bdddae2c747047b4a3694c7060/HiVision_code/vision.cpp#L239) is too long. Please modularize it into documented functions.

**Comment by MemoryMmy** [comment]
Thanks for pointing out this issue. I have modularized the main codes (src/server.cpp src/vision.cpp) into functions.

**Comment by r-barnes** [comment]
Thank you, I appreciate this. Increased modularization could still improve the code.

I'd also recommend, in future work, to standardize to using only spaces for indentation. The current project mixes spaces and tabs in a way which makes the code hard to read. A style checker like [clang-format](https://clang.llvm.org/docs/ClangFormat.html) can be helpful here.
