### ISSUE TITLE
Code is undocumented

### ISSUE THREAD

**Issue by r-barnes** [MemoryMmy/HiVision#4]
The code should contain internal comments which explain what it does and why design decisions have been made.

**Comment by MemoryMmy** [comment]
I have added some descriptions for the functions.

**Comment by r-barnes** [comment]
I don't think this is really sufficient.

The best way of doing these function descriptions is with DOxygen-style comment strings. Those look like [this](https://embeddedinventor.com/guide-to-configure-doxygen-to-document-c-source-code-for-beginners/) and [this](http://fnch.users.sourceforge.net/doxygen_c.html) and allow you to generate HTML and PDF use-guides like [this](http://cs.smu.ca/~porter/csc/common_341_342/doxygen/html/doxygen__example_8cpp.html) and [this](http://richdem.com/cpp_api.html). They are also used by editors like VSCode to provide help pop-ups while you program, making it easier for you and others to work with your code.

The functions themselves also lack internal documentation: we might know what the function does, but there are not internal comments regarding how it's doing it.

**Comment by MemoryMmy** [comment]
I have enriched the descriptions of the functions and modified the variable names in the code to be consistent with the pseudocode in the manuscript.

**Comment by r-barnes** [comment]
Note that it would be quicker for me to check your changes if your commit messages were more informative: you have made four recently that are only labeled "Update".

**Comment by r-barnes** [comment]
It looks as though most of these changes are made in 8566a1bc239dd6b45cfea33702a8b96c938672d8.

**Comment by r-barnes** [comment]
Thanks, this looks much better.
