### ISSUE TITLE
What is the `visioncrowserver` directory?

### ISSUE THREAD

**Issue by r-barnes** [MemoryMmy/HiVision#5]
What is the `visioncrowserver` directory? It isn't included in the main Makefile or mentioned in the README.

Please be sure that a single `CMakeLists.txt` file will compile all necessary code, possibly by calling to similar files in subdirectories.

**Comment by MemoryMmy** [comment]
I have removed the visioncrowserver directory in Version 0.2.0.

**Comment by r-barnes** [comment]
Thanks!
