### ISSUE TITLE
Bash scripts should begin with she-bang

### ISSUE THREAD

**Issue by r-barnes** [MemoryMmy/HiVision#7]
Bash scripts should begin with `#!/bin/bash` (or similar call) following the standard [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) syntax.

**Comment by MemoryMmy** [comment]
I have added #!/bin/bash in start.sh and stop.sh.

**Comment by r-barnes** [comment]
Thanks!

`set -ex` is also a good line to include, see [this link](https://www.peterbe.com/plog/set-ex).
