### ISSUE TITLE
Document `onlinedemo`

### ISSUE THREAD

**Issue by r-barnes** [MemoryMmy/HiVision#8]
Your `onlinedemo` directory is not well-documented. What are the subdirectories for? How are they used?

**Comment by MemoryMmy** [comment]
I have removed the onlinedemo directory in Version 0.2.0 as it does not belong to the functional code of HiVison.  The onlinedemo directory contains the webpages of Online Demo1 (http://www.higis.org.cn:8080/hivision/)  and Online Demo2(http://www.higis.org.cn:8080/hivision_with_pattern/).

**Comment by r-barnes** [comment]
I'd appreciate having this client code included so that the repo is able to demonstrate itself, since "http://www.higis.org.cn:8080/hivision/" may break at some point in the future.

**Comment by MemoryMmy** [comment]
We have added the code of the online demos to the project.

**Comment by r-barnes** [comment]
Thanks.
